USE [Libol]
GO

/****** Object:  Table [dbo].[FPT_RECOMMEND]    Script Date: 07/07/2019 19:01:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FPT_RECOMMEND](
	[POID] [int] NOT NULL,
	[ReID] [varchar](30) NOT NULL,
 CONSTRAINT [PK_FPT_RECOMMEND] PRIMARY KEY CLUSTERED 
(
	[POID] ASC,
	[ReID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FPT_RECOMMEND]  WITH CHECK ADD  CONSTRAINT [FK_FPT_RECOMMEND_ACQ_PO] FOREIGN KEY([POID])
REFERENCES [dbo].[ACQ_PO] ([ID])
GO

ALTER TABLE [dbo].[FPT_RECOMMEND] CHECK CONSTRAINT [FK_FPT_RECOMMEND_ACQ_PO]
GO


