CREATE PROCEDURE [dbo].[FPT_ADMIN_GET_RIGHTS_DENY]
	@intModuleID int,
	@intUserID int
AS

SELECT R.ID, R.[Right] FROM SYS_USER_RIGHT R WHERE R.ModuleID = @intModuleID AND R.ID NOT IN (
	SELECT U.ID FROM SYS_USER_RIGHT_DETAIL D JOIN SYS_USER_RIGHT U ON D.RightID = U.ID
	WHERE D.UserID = @intUserID AND U.ModuleID = @intModuleID
)